[package]
name = "spectrum"
version = "0.1.0"
authors = ["Kamil Rusin"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
fern = "0.6"
futures-util = "0.3"
log = "0.4"
prost = "0.11"
tokio = { version = "1.20", features = ["macros", "rt-multi-thread", "sync"] }
tokio-tungstenite = "0.17"
tungstenite = "0.17"

[build-dependencies]
prost-build = "0.11"
