[package]
name = "spectrum-packet"
version = "0.1.0"
authors = ["Kamil Rusin"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
prost = "0.11"

[build-dependencies]
prost-build = "0.11"
